global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'strategies'
    static_configs:
      - targets: ['host.docker.internal:9090', 'host.docker.internal:9091', 'host.docker.internal:9092']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*:9090'
        target_label: strategy
        replacement: 'Trend Following'
      - source_labels: [__address__]
        regex: '.*:9091'
        target_label: strategy
        replacement: 'Market Making'
      - source_labels: [__address__]
        regex: '.*:9092'
        target_label: strategy
        replacement: 'Funding Arb'
